#!/usr/bin/env bash
# ============================================================================
# clone-app-config.sh — Nhân bản cấu hình cho hệ thống thứ 2, 3
# ============================================================================
# Script này sinh ra bộ config (PM2 + Nginx + deploy.sh) cho 1 app mới trên
# VPS, dựa trên template đã có cho hệ thống hiện tại (epath-training).
#
# Sử dụng:
#   bash scripts/clone-app-config.sh <app-name> <port> <domain> [--new-firebase]
#
# Ví dụ:
#   bash scripts/clone-app-config.sh he-thong-2 3001 he-thong-2.id.vn
#   bash scripts/clone-app-config.sh he-thong-3 3002 he-thong-3.id.vn --new-firebase
#
# Sau khi chạy script:
#   - Folder /var/www/<app-name> được tạo
#   - /etc/<app-name>/.env được tạo (template rỗng)
#   - File config (ecosystem, nginx, deploy) được sinh ra
#   - Nếu --new-firebase: gọi setup-firebase.sh để tạo Firebase project
# ============================================================================

set -euo pipefail

APP_NAME="${1:-}"
PORT="${2:-}"
DOMAIN="${3:-}"
NEW_FIREBASE=false

# Parse optional flag
for arg in "$@"; do
  case "$arg" in
    --new-firebase) NEW_FIREBASE=true ;;
  esac
done

# --- Validate ---
if [ -z "$APP_NAME" ] || [ -z "$PORT" ] || [ -z "$DOMAIN" ]; then
  echo "Usage: $0 <app-name> <port> <domain> [--new-firebase]"
  echo ""
  echo "Arguments:"
  echo "  app-name      Tên app (lowercase, alphanumeric, hyphens)"
  echo "  port          Port số (3001, 3002, ...)"
  echo "  domain        Domain/subdomain (vd: he-thong-2.id.vn)"
  echo "  --new-firebase  Tùy chọn: tự tạo Firebase project mới"
  echo ""
  echo "Examples:"
  echo "  $0 he-thong-2 3001 he-thong-2.id.vn"
  echo "  $0 he-thong-3 3002 he-thong-3.id.vn --new-firebase"
  exit 1
fi

# Validate app name
if ! [[ "$APP_NAME" =~ ^[a-z0-9-]+$ ]]; then
  echo "ERROR: app-name must be lowercase alphanumeric with hyphens"
  exit 1
fi

# Validate port
if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [ "$PORT" -lt 3000 ] || [ "$PORT" -gt 65535 ]; then
  echo "ERROR: port must be 3000-65535"
  exit 1
fi

# Validate domain
if ! [[ "$DOMAIN" =~ ^[a-zA-Z0-9.-]+\.[a-z]{2,}$ ]]; then
  echo "ERROR: invalid domain format: $DOMAIN"
  exit 1
fi

APP_DIR="/var/www/$APP_NAME"
ENV_DIR="/etc/$APP_NAME"
ENV_FILE="$ENV_DIR/.env"
LOG_DIR="/var/log/pm2/$APP_NAME"

echo "==> Cloning config for $APP_NAME (port $PORT → $DOMAIN)"

# --- Tạo folders ---
echo "==> [1/6] Creating folders..."
mkdir -p "$APP_DIR" "$ENV_DIR" "$LOG_DIR"

# --- Generate ecosystem.config.js ---
echo "==> [2/6] Generating ecosystem.config.js..."
cat > "$APP_DIR/ecosystem.config.js" <<EOF
/**
 * PM2 Ecosystem config cho $APP_NAME
 * Auto-generated by clone-app-config.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
 *
 * Deploy: pm2 start ecosystem.config.js --env production
 * Reload: pm2 reload ecosystem.config.js --env production
 */
module.exports = {
  apps: [
    {
      name: "$APP_NAME",
      script: "./node_modules/next/dist/bin/next",
      args: "start -p $PORT -H 0.0.0.0",
      instances: "max",
      exec_mode: "cluster",
      autorestart: true,
      max_memory_restart: "500M",
      listen_timeout: 3000,
      kill_timeout: 5000,
      error_file: "$LOG_DIR/error.log",
      out_file: "$LOG_DIR/out.log",
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: "production",
        PORT: "$PORT",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: "$PORT",
      },
    },
  ],
};
EOF

# --- Generate nginx config ---
echo "==> [3/6] Generating nginx config..."
cat > "/etc/nginx/sites-available/$APP_NAME.conf" <<EOF
# Nginx reverse proxy for $APP_NAME
# Domain: $DOMAIN → upstream port $PORT

upstream ${APP_NAME//-/_}_app {
    server 127.0.0.1:$PORT;
    keepalive 64;
}

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
        proxy_buffering       off;
        client_max_body_size  50M;
    }
}
EOF

# --- Generate deploy.sh (từ template, sed các giá trị) ---
echo "==> [4/6] Generating deploy.sh..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

if [ -f "$REPO_ROOT/deploy.sh" ]; then
  sed -e "s|/var/www/epath-training|$APP_DIR|g" \
      -e "s|/etc/epath-training/.env|$ENV_FILE|g" \
      -e "s|/var/log/pm2/epath-training|$LOG_DIR|g" \
      -e "s|127.0.0.1:3000|127.0.0.1:$PORT|g" \
      -e "s|\"epath-training\"|\"$APP_NAME\"|g" \
      "$REPO_ROOT/deploy.sh" > "$APP_DIR/deploy.sh"
  chmod +x "$APP_DIR/deploy.sh"
else
  echo "WARN: $REPO_ROOT/deploy.sh not found — skipping deploy.sh generation"
fi

# --- Generate .env file (template rỗng) ---
echo "==> [5/6] Generating env template..."
cat > "$ENV_FILE" <<EOF
# Environment for $APP_NAME — fill values and chmod 600
# Generated by clone-app-config.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=

NEXT_PUBLIC_APP_NAME=$APP_NAME
NEXT_PUBLIC_APP_URL=https://$DOMAIN

FIREBASE_ADMIN_PROJECT_ID=
FIREBASE_ADMIN_CLIENT_EMAIL=
FIREBASE_ADMIN_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nFILL_ME\n-----END PRIVATE KEY-----\n"

S3_ENDPOINT=
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET=
S3_REGION=ap-southeast-1
S3_USE_LOCAL_FALLBACK=0

STREAM_SESSION_SECRET=$(openssl rand -base64 48 | tr -d '\n')

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
EOF

chmod 600 "$ENV_FILE"

# --- Enable nginx site + reload ---
echo "==> [6/6] Enabling nginx site..."
if [ -d /etc/nginx/sites-enabled ]; then
  ln -sf "/etc/nginx/sites-available/$APP_NAME.conf" \
         "/etc/nginx/sites-enabled/$APP_NAME.conf"
  nginx -t && systemctl reload nginx && echo "  nginx reloaded OK" \
    || echo "  WARN: nginx reload failed — check config manually"
else
  echo "  WARN: /etc/nginx/sites-enabled not found"
fi

# --- Optional: create new Firebase project ---
if $NEW_FIREBASE; then
  echo ""
  echo "==> Creating new Firebase project..."
  FIREBASE_ID="${APP_NAME//-/_}_prod_$(date +%s | tail -c 5)"
  if [ -f "$REPO_ROOT/scripts/setup-firebase.sh" ]; then
    bash "$REPO_ROOT/scripts/setup-firebase.sh" "$FIREBASE_ID" "$APP_NAME" || {
      echo "WARN: Firebase setup failed. Run manually later."
    }
  fi
fi

echo ""
echo "==> DONE! $APP_NAME config cloned successfully."
echo ""
echo "  NEXT STEPS:"
echo "  1. Clone repo code mới vào $APP_DIR:"
echo "     git clone <repo-url> $APP_DIR"
echo "  2. Điền env thật:"
echo "     sudo nano $ENV_FILE"
echo "  3. Cài deps + build + start:"
echo "     cd $APP_DIR && npm ci --omit=dev && npm run build"
echo "     pm2 start ecosystem.config.js --env production"
echo "     pm2 save"
echo "  4. Cài SSL:"
echo "     certbot --nginx -d $DOMAIN -d www.$DOMAIN"
echo ""
echo "  Files created:"
echo "    - $APP_DIR/ecosystem.config.js"
echo "    - $APP_DIR/deploy.sh"
echo "    - /etc/nginx/sites-available/$APP_NAME.conf"
echo "    - $ENV_FILE"
echo "    - $LOG_DIR/"
