#!/usr/bin/env bash
# ============================================================================
# setup-firebase.sh — Tạo Firebase project mới cho hệ thống thứ 2, 3
# ============================================================================
# Script này DÙNG KHI triển khai các hệ thống tiếp theo (app 2, app 3) trên
# cùng VPS, mỗi hệ thống cần 1 Firebase project RIÊNG.
#
# Với hệ thống hiện tại (epath-training), KHÔNG cần chạy script này —
# đã dùng project epath-f6277 có sẵn, copy từ env-vercel.env.
#
# Yêu cầu:
#   - Đã cài Firebase CLI: npm install -g firebase-tools
#   - Đã login: firebase login
#   - Có quyền tạo project trong tổ chức Firebase
#
# Sử dụng:
#   bash scripts/setup-firebase.sh <project-id> <app-name>
#   Ví dụ: bash scripts/setup-firebase.sh epath-system-2-prod he-thong-2
# ============================================================================

set -euo pipefail

PROJECT_ID="${1:-}"
APP_NAME="${2:-}"

if [ -z "$PROJECT_ID" ] || [ -z "$APP_NAME" ]; then
  echo "Usage: $0 <firebase-project-id> <app-name>"
  echo "Example: $0 epath-system-2-prod he-thong-2"
  exit 1
fi

# Validate project id (lowercase, alphanumeric, hyphens, 6-30 chars)
if ! [[ "$PROJECT_ID" =~ ^[a-z0-9-]{6,30}$ ]]; then
  echo "ERROR: Invalid Firebase project id: $PROJECT_ID"
  echo "Must be 6-30 chars, lowercase, alphanumeric and hyphens only."
  exit 1
fi

ENV_OUT="/etc/${APP_NAME}/.env"
mkdir -p "/etc/${APP_NAME}"

echo "==> [1/8] Checking Firebase CLI..."
command -v firebase >/dev/null || {
  echo "ERROR: firebase CLI not installed. Run: npm install -g firebase-tools"
  exit 1
}
firebase login:list >/dev/null 2>&1 || {
  echo "ERROR: Not logged in. Run: firebase login"
  exit 1
}

echo "==> [2/8] Creating Firebase project: $PROJECT_ID"
firebase projects:create "$PROJECT_ID" --display-name "$APP_NAME" || {
  echo "WARN: Project may already exist. Continuing..."
}

echo "==> [3/8] Enabling services (Auth, Firestore, Storage)..."
# Auth
echo "  - Enabling Authentication..."
firebase --project "$PROJECT_ID" auth:enable --force 2>/dev/null || true
# Firestore
echo "  - Enabling Firestore (default DB, asia-southeast1)..."
firebase --project "$PROJECT_ID" firestore:databases:create \
  --location asia-southeast1 --default 2>/dev/null || \
  echo "  - Firestore already exists"
# Storage
echo "  - Enabling Storage..."
firebase --project "$PROJECT_ID" storage:bucket:create \
  --location asia-southeast1 2>/dev/null || \
  echo "  - Storage bucket already exists"

echo "==> [4/8] Creating Web App..."
APP_OUTPUT=$(firebase --project "$PROJECT_ID" apps:create web "$APP_NAME" \
  --display-name "$APP_NAME" 2>/dev/null) || {
  echo "WARN: Web app may already exist. Listing apps..."
  firebase --project "$PROJECT_ID" apps:list --json
}
echo "$APP_OUTPUT"

# --- Hướng dẫn user lấy config thủ công ---
echo ""
echo "  >> TIP: Lấy Firebase Web App config bằng:"
echo "     firebase --project $PROJECT_ID apps:config web"
echo "     Copy apiKey, authDomain, projectId, storageBucket, messagingSenderId, appId"
echo ""

echo "==> [5/8] Generating service account key..."
KEY_FILE="/tmp/${APP_NAME}-firebase-key-$$.json"
firebase --project "$PROJECT_ID" iam:service-accounts:create \
  "firebase-admin-${APP_NAME}" \
  --display-name "Firebase Admin for $APP_NAME" 2>/dev/null || true

firebase --project "$PROJECT_ID" iam:service-accounts:keys:create \
  "firebase-admin-${APP_NAME}@${PROJECT_ID}.iam.gserviceaccount.com" \
  --output "$KEY_FILE" || {
  echo "ERROR: Cannot create service account key. Create manually in console."
}

if [ -f "$KEY_FILE" ]; then
  PROJECT_ID_VAL=$(jq -r '.project_id' "$KEY_FILE")
  CLIENT_EMAIL=$(jq -r '.client_email' "$KEY_FILE")
  PRIVATE_KEY=$(jq -r '.private_key' "$KEY_FILE")
  rm -f "$KEY_FILE"
else
  PROJECT_ID_VAL="$PROJECT_ID"
  CLIENT_EMAIL=""
  PRIVATE_KEY=""
fi

echo "==> [6/8] Generating random secrets..."
STREAM_SECRET=$(openssl rand -base64 48 | tr -d '\n')

echo "==> [7/8] Writing env file to $ENV_OUT..."

cat > "$ENV_OUT" <<EOF
# ============================================================================
# Generated by setup-firebase.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Project: $PROJECT_ID
# App: $APP_NAME
# ============================================================================

# Firebase Client (lấy từ: firebase apps:config web)
NEXT_PUBLIC_FIREBASE_API_KEY=REPLACE_ME
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${PROJECT_ID_VAL}.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${PROJECT_ID_VAL}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${PROJECT_ID_VAL}.firebasestorage.app
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=REPLACE_ME
NEXT_PUBLIC_FIREBASE_APP_ID=REPLACE_ME
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=

# App Metadata
NEXT_PUBLIC_APP_NAME=$APP_NAME
NEXT_PUBLIC_APP_URL=https://${APP_NAME}.lp-intranet.id.vn

# Firebase Admin SDK
FIREBASE_ADMIN_PROJECT_ID=${PROJECT_ID_VAL}
FIREBASE_ADMIN_CLIENT_EMAIL=${CLIENT_EMAIL}
FIREBASE_ADMIN_PRIVATE_KEY="${PRIVATE_KEY}"

# Viettel IDC S3 Storage (copy từ env-vercel.env hệ thống gốc)
S3_ENDPOINT=
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET=
S3_REGION=ap-southeast-1
S3_USE_LOCAL_FALLBACK=0

# Streaming session secret
STREAM_SESSION_SECRET=${STREAM_SECRET}

# SMTP Email
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
EOF

chmod 600 "$ENV_OUT"

echo "==> [8/8] Done!"
echo ""
echo "  NEXT STEPS:"
echo "  1. Điền các giá trị REPLACE_ME trong $ENV_OUT:"
echo "     sudo nano $ENV_OUT"
echo "  2. Copy code repo mới vào /var/www/$APP_NAME"
echo "  3. Chạy: cd /var/www/$APP_NAME && bash deploy.sh"
echo "  4. Cấu hình Nginx cho domain tương ứng"
echo ""
echo "  >> Backup file env ở chỗ an toàn. Mất file này = phải tạo lại key."
